/* global globalThis */

// TODO: type support via generated bindings

/**
 * This file implements helpers and relevant types for use with `wasi:http` 0.2.x APIs
 *
 * @see: https://github.com/WebAssembly/wasi-http
 */

/** Get the global `Request` */
function ensureGlobalRequest() {
    if (!globalThis.Request) {
        throw new TypeError('Request not provided by platform');
    }
    return globalThis.Request;
}

/** Convert a `wasi:http` `method` to a string */
function wasiHTTPMethodToString(wasiMethod) {
    if (!wasiMethod?.tag) {
        throw new TypeError(
            'invalid wasi HTTP method variant, does not contain tag'
        );
    }
    switch (wasiMethod.tag) {
        case 'get':
        case 'head':
        case 'post':
        case 'put':
        case 'delete':
        case 'connect':
        case 'options':
        case 'trace':
        case 'patch':
            return wasiMethod.tag.toUpperCase();
        case 'other':
            if (!wasiMethod.val || typeof wasiMethod.val !== 'string') {
                throw new TypeError(
                    "HTTP method variant 'other' with missing/invaldi payload"
                );
            }
            return wasiMethod.val;
        default:
            throw new TypeError(
                `unrecognized wasi HTTP method tag [${wasiMethod.tag}]`
            );
    }
}

/**
 * Create a web-platform `Request` from a `wasi:http/incoming-handler` `incoming-request`.
 *
 * This method expects the `wasiIncomingRequest` object to be compliant with WASI 0.2.x,
 * with an implemention as generated by the jco/componentize-js JS ecosystem.
 *
 * @param {any} wasiIncomingRequest - request handler for a WASI HTTP request
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/Request
 * @see https://github.com/WebAssembly/wasi-http
 */
export async function createWebPlatformRequest(wasiIncomingRequest) {
    if (wasiIncomingRequest) {
        throw new TypeError('WASI incoming request not provided');
    }
    const method = wasiHTTPMethodToString(wasiIncomingRequest.method());
    const pathWithQuery = wasiIncomingRequest.pathWithQuery();
    const scheme = wasiIncomingRequest.scheme();
    const authority = wasiIncomingRequest.authority();
    const headers = Object.fromEntries(wasiIncomingRequest.headers().entries());
    const Request = ensureGlobalRequest();
    return new Request(`${scheme}://${authority}/${pathWithQuery}`, {
        method,
        headers,
    });
}
